name: 'build and deploy Speckle functions'
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-automate-function-version:
    env:
      FUNCTION_SCHEMA_FILE_NAME: functionSchema.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.20'

      # Build the Go binary
      - name: Build Go binary
        run: go build -o speckle_function ./cmd/main.go

      # If you need to generate schema, you would do it here
      # If your Go application can generate the function schema, use the Go binary to do so
      - name: Extract functionInputSchema
        id: extract_schema
        run: ./speckle_function generate-schema ${HOME}/${{ env.FUNCTION_SCHEMA_FILE_NAME }}

      # Speckle Automate Function - Build and Publish
      - name: Speckle Automate Function - Build and Publish
        uses: specklesystems/speckle-automate-github-composite-action@0.8.1
        with:
          speckle_automate_url: ${{ env.SPECKLE_AUTOMATE_URL || 'https://automate.speckle.dev' }} 
          speckle_token: ${{ secrets.SPECKLE_FUNCTION_TOKEN }}
          speckle_function_id: ${{ secrets.SPECKLE_FUNCTION_ID }}
          speckle_function_input_schema_file_path: ${{ env.FUNCTION_SCHEMA_FILE_NAME }}
          speckle_function_command: './speckle_function run'  # Use the Go binary instead of a Python script
          speckle_function_recommended_cpu_m: 4000
          speckle_function_recommended_memory_mi: 4000
